### PR TITLE
show the install result and add verbose option

### LINKED ISSUE #42: Add verbose option
Hi all. I love this project!

I'm using brewdle **right now** to setup a new machine. And its seems to be going smoothly, but... The output is blank! The only thing I got for this Brewfile:

```ruby
# Packages
brew 'zsh'
brew 'git'
brew 'rbenv'
brew 'ruby-build'
brew 'vim', args: ['override-system-vi']
brew 'node'
brew 'python'
brew 'brew-cask'
brew 'imagemagick'

# Apps
tap 'caskroom/cask'

cask 'iterm2'
cask 'google-chrome'
cask 'alfred'
# more stuff...
```

was 

```
$ brew brewdle
Error: No available formula for brew-cask 
Cloning into '/usr/local/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 124686, done.
remote: Compressing objects: 100% (63/63), done.
remote: Total 124686 (delta 33), reused 2 (delta 0)
Receiving objects: 100% (124686/124686), 34.34 MiB | 1.29 MiB/s, done.
Resolving deltas: 100% (82534/82534), done.
Checking connectivity... done.
Error: Unknown command: cask
Error: Unknown command: cask
Error: Unknown command: cask
...
```

I was expecting some output like `successfully installed 'zsh'`. I think either adding redirecting brew's stdout by default, or at lest adding a verbose option, would be a nice improvement.

### PR DESCRIPTION
**Pull request by xu-cheng**
Close #42

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Verbose flag would be good but what might be even better is if we could capture the output and only output it on failure or verbose being enabled. What do you think?

**Comment by xu-cheng** [comment]
Yeah, that's great idea. I will explore it in the weekend.

**Comment by xu-cheng** [comment]
@mikemcquaid Updated with your idea and adding test for it.

**Comment by xu-cheng** [comment]
The coverage got confused by these subprocess, which results to a drop in the coverage.

File: lib/brewdler/utils.rb [hunk 1]
```diff
@@ -1,10 +1,29 @@
...
+      end
+
+      wr.close
+      while buf = rd.gets
+        puts buf if verbose
+        logs << buf
+      end
+    rescue
+      rd.close
     end
```
Comment (mikemcquaid) [inline lib/brewdler/utils.rb]: I really think `IO.popen` would allow this code to be significantly simpler. If you need a hand here I can try and work on my own implementation and post it?

Comment (xu-cheng) [inline lib/brewdler/utils.rb]: Yeah, why not? I can also learn things from you. :smile:

Comment (xu-cheng) [inline lib/brewdler/utils.rb]: @mikemcquaid Have you working on this using `IO.popen`?

I planned to implement `brew brewdle cleanup` in this way:
Merge this PR -> new PR to decouple parsing Brewfile and actual installation -> `brew brewdle cleanup`

Comment (mikemcquaid) [inline lib/brewdler/utils.rb]: Still on my TODO list, sorry :sob:

**Comment by xu-cheng** [comment]
@mikemcquaid I rewrite the way to show the result which combines your advice from #47.

File: lib/brewdler/utils.rb (hunk 1 above)
Comment (mikemcquaid) [inline lib/brewdler/utils.rb]: I don't want to block this being included but https://github.com/mikemcquaid/HookHand/blob/028a138c0b8f76e9e3baf7a71619b069755d3b5e/hookhand.rb#L137-L160 should show a use of `IO.popen` which will hopefully clarify things. If it's still too confusing feel free to say so and we can just merge this as-is.

**Comment by xu-cheng** [comment]
@mikemcquaid Rewrite using `IO.popen`. Ask for review.

File: lib/brewdler/utils.rb [hunk 2]
```diff
@@ -1,11 +1,19 @@
...
+        logs << buf
+      end
+      Process.wait(pipe.pid)
+      success = $?.success?
+      pipe.close
     end
-    Process.wait(pid)
-    $?.success?
+    puts logs.join unless success || verbose
+    success
```
Comment (mikemcquaid) [inline lib/brewdler/utils.rb]: :heart_eyes:

**Comment by mikemcquaid** [comment]
Merge when green!

**Comment by xu-cheng** [comment]
Now it's green :rocket:

**Comment by mikemcquaid** [comment]
@xu-cheng Can you self-merge this? If not, I'll give you access to this repo. You can use the merge button here :grinning:

**Comment by xu-cheng** [comment]
No, I have no access to this repo.

**Comment by mikemcquaid** [comment]
You do now.

**Comment by xu-cheng** [comment]
Thanks :shipit:
